# Generated by Django 3.0.3 on 2023-06-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
